### ISSUE TITLE
Add scale option

### ISSUE THREAD

**Issue by domoritz** [NotNinja/convert-svg-to-png#3]
I'd love to scale all generated images to be 2x the resolution in the SVG.

**Comment by neocotic** [comment]
I like this idea!

What about cases where the size cannot be derived from the image and the width/height is required? Would you expect the scale option to be applied to the width/height options or completely ignored and the width/height options always taken as explicit? I'm for the latter as, if the width/height is specified explicitly, the developer could have simply multiplied them already to their own scale.

Thoughts?

**Comment by domoritz** [comment]
I think both make sense. Intuitively, I'd have used the first option
because then all pixel units are in the same scale. Also, the 2x for hidpi
screens requires devs to write in terms of pixels before scaling.

I'd check what other libraries that support scaling are doing.

**Comment by neocotic** [comment]
I'll implement this initially based on the `scale` option being applied to any specified or derived dimensions with a default of `1` and we can change in the future based on feedback. This is a very immature package, so I'm happy to make changes like this now and improve in the future, if needed.

**Comment by domoritz** [comment]
Fantastic!

**Comment by neocotic** [comment]
This work has been delivered by PR #11. It will be included in the upcoming 0.2.0 release.

**Comment by neocotic** [comment]
@domoritz I've just release v0.2.0. Check it out and let me know how you get on. There's some minor breaking changes to the API, but nothing I expect to affect many users considering how new this package is.
